### ISSUE TITLE
Add parameter for maximum comment width

### ISSUE THREAD

**Issue by Plecra** [Byron/prodash#1]
https://asciinema.org/a/346619

In this demo, the left side of the progress bars jumps around. It looks like it's trying to keep the set of bars aligned, and when the comments change, it can take more space.

It'd be nice to be able to set that indent to a fixed value to avoid this behavior

**Comment by Byron** [comment]
I believe what you are look for [does already exist](https://docs.rs/prodash/7.0.3/prodash/tui/struct.Options.html#structfield.recompute_column_width_every_nth_frame) - setting this value very high should prevent any dynamic recomputation.

Please let me know if there is anything else needed to get the behaviour you seek, and we can flesh it out here.
